---
- name: set up spack profile scripts
  template:
    src: "{{ item }}"
    dest: "/etc/profile.d/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
  - "z00_spack.sh"
  - "z00_spack.csh"
  - "z00_spack.zsh"

- name: source zsh profile on login
  lineinfile:
    dest: /etc/zsh/zprofile
    insertafter: EOF
    line: 'source /etc/profile.d/z00_spack.zsh'
  register: update_zsh_spack