---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  tasks:
  - name: Install Node Health Check
    # The NHC role declares the facts role as a dependency.
    include_role:
      name: nhc
